/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import controller.MovieController;
import models.Winner;

import static javax.swing.JOptionPane.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import java.util.*;
import java.util.regex.Pattern;
import java.util.regex.Matcher;
import java.awt.Graphics;
import java.awt.image.*;

/**
 *
 * @author Egor
 */
public class GUI extends javax.swing.JFrame  {
private MovieController mc=new MovieController();  ; // для работы в интерфейсе
private Winner winner=new Winner();
public boolean click=false;
public static int count;
    /**
     * Creates new form GUI
     */
Tournament tournament=new Tournament();
    public GUI() {

       tournament=new Tournament(mc.getAllMovies());
       this.setResizable(false);      
       initComponents();
       ChoicePanel.setVisible(false);   //игровая панель с выбором сущностей
       ChampPanel.setVisible(false);  //вывод победителя
       SessionsPanel.setVisible(false); //список сущностей
       LastChampPanel.setVisible(false); //список сущностей
       this.setDefaultCloseOperation(EXIT_ON_CLOSE);
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
   
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChampPanel = new javax.swing.JPanel();
        ChampLabel = new javax.swing.JLabel();
        WinnerButton = new javax.swing.JButton();
        AgainButton = new javax.swing.JButton();
        EndButton = new javax.swing.JButton();
        MainPanel = new javax.swing.JPanel();
        BeginButton = new javax.swing.JButton();
        SessionButton = new javax.swing.JButton();
        ExitButton = new javax.swing.JButton();
        ChoicePanel = new javax.swing.JPanel();
        LeftButton = new javax.swing.JButton();
        RightButton = new javax.swing.JButton();
        ChoiceLabel = new javax.swing.JLabel();
        LeftLabel = new javax.swing.JLabel();
        RightLabel = new javax.swing.JLabel();
        LastChampPanel = new javax.swing.JPanel();
        SessionsPanel = new javax.swing.JPanel();
        ListLabel = new javax.swing.JLabel();
        BackButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ChoiceTheBest");
        setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        setForeground(java.awt.Color.blue);
        setMaximumSize(new java.awt.Dimension(900, 710));
        setPreferredSize(new java.awt.Dimension(900, 700));

        ChampPanel.setBackground(new java.awt.Color(51, 0, 102));
        ChampPanel.setMaximumSize(new java.awt.Dimension(800, 400));
        ChampPanel.setPreferredSize(new java.awt.Dimension(800, 400));

        ChampLabel.setBackground(new java.awt.Color(204, 255, 255));
        ChampLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ChampLabel.setForeground(new java.awt.Color(255, 255, 0));
        ChampLabel.setText("Победитель!!!");
        ChampLabel.setToolTipText("");

        WinnerButton.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        WinnerButton.setForeground(new java.awt.Color(153, 0, 0));
        WinnerButton.setToolTipText("");

        AgainButton.setBackground(new java.awt.Color(255, 255, 51));
        AgainButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgainButton.setText("Начать заново");
        AgainButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgainButtonActionPerformed(evt);
            }
        });

        EndButton.setBackground(new java.awt.Color(255, 255, 51));
        EndButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        EndButton.setText("Завершить");
        EndButton.setToolTipText("");
        EndButton.setPreferredSize(new java.awt.Dimension(141, 25));
        EndButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EndButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ChampPanelLayout = new javax.swing.GroupLayout(ChampPanel);
        ChampPanel.setLayout(ChampPanelLayout);
        ChampPanelLayout.setHorizontalGroup(
            ChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChampPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(AgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EndButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
            .addGroup(ChampPanelLayout.createSequentialGroup()
                .addGroup(ChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ChampPanelLayout.createSequentialGroup()
                        .addGap(330, 330, 330)
                        .addComponent(ChampLabel))
                    .addGroup(ChampPanelLayout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(WinnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(208, Short.MAX_VALUE))
        );
        ChampPanelLayout.setVerticalGroup(
            ChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ChampPanelLayout.createSequentialGroup()
                .addGroup(ChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ChampPanelLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(ChampLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WinnerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(ChampPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EndButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgainButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28))
        );

        MainPanel.setBackground(new java.awt.Color(51, 0, 102));
        MainPanel.setForeground(new java.awt.Color(255, 255, 255));
        MainPanel.setMaximumSize(new java.awt.Dimension(800, 400));
        MainPanel.setPreferredSize(new java.awt.Dimension(800, 400));

        BeginButton.setBackground(new java.awt.Color(255, 255, 0));
        BeginButton.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        BeginButton.setText("НАЧАТЬ");
        BeginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeginButtonActionPerformed(evt);
            }
        });

        SessionButton.setBackground(new java.awt.Color(255, 255, 0));
        SessionButton.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        SessionButton.setText("<html>\nПредыдущие <br>\n <center>\n   сеансы\n</center>\n</html>\n");
        SessionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SessionButtonActionPerformed(evt);
            }
        });

        ExitButton.setBackground(new java.awt.Color(255, 255, 0));
        ExitButton.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        ExitButton.setText("ВЫХОД");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BeginButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ExitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SessionButton))
                .addContainerGap(237, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(BeginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(SessionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(ExitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        ChoicePanel.setBackground(new java.awt.Color(51, 0, 102));
        ChoicePanel.setMaximumSize(new java.awt.Dimension(800, 400));
        ChoicePanel.setPreferredSize(new java.awt.Dimension(800, 400));

        LeftButton.setBackground(new java.awt.Color(204, 204, 204));
        LeftButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LeftButton.setForeground(new java.awt.Color(0, 0, 102));
        LeftButton.setName("LeftButton"); // NOI18N
        LeftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeftButtonActionPerformed(evt);
            }
        });

        RightButton.setBackground(new java.awt.Color(204, 204, 204));
        RightButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RightButton.setForeground(new java.awt.Color(0, 0, 102));
        RightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RightButtonActionPerformed(evt);
            }
        });

        ChoiceLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        ChoiceLabel.setForeground(new java.awt.Color(255, 255, 0));
        ChoiceLabel.setText("Выберите лучшего:");

        LeftLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        LeftLabel.setForeground(new java.awt.Color(255, 255, 0));

        RightLabel.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        RightLabel.setForeground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout ChoicePanelLayout = new javax.swing.GroupLayout(ChoicePanel);
        ChoicePanel.setLayout(ChoicePanelLayout);
        ChoicePanelLayout.setHorizontalGroup(
            ChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoicePanelLayout.createSequentialGroup()
                .addGap(254, 254, 254)
                .addComponent(ChoiceLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ChoicePanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(ChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LeftLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(ChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RightLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
        );
        ChoicePanelLayout.setVerticalGroup(
            ChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ChoicePanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(ChoiceLabel)
                .addGap(18, 18, 18)
                .addGroup(ChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LeftButton, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RightButton, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ChoicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LeftLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(RightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        LastChampPanel.setBackground(new java.awt.Color(51, 0, 102));

        javax.swing.GroupLayout LastChampPanelLayout = new javax.swing.GroupLayout(LastChampPanel);
        LastChampPanel.setLayout(LastChampPanelLayout);
        LastChampPanelLayout.setHorizontalGroup(
            LastChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        LastChampPanelLayout.setVerticalGroup(
            LastChampPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        SessionsPanel.setBackground(new java.awt.Color(51, 0, 102));
        SessionsPanel.setPreferredSize(new java.awt.Dimension(900, 700));

        ListLabel.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        ListLabel.setForeground(new java.awt.Color(255, 255, 0));
        ListLabel.setText("Список доступных сессий:");

        BackButton.setBackground(new java.awt.Color(255, 255, 0));
        BackButton.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        BackButton.setText("Назад");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SessionsPanelLayout = new javax.swing.GroupLayout(SessionsPanel);
        SessionsPanel.setLayout(SessionsPanelLayout);
        SessionsPanelLayout.setHorizontalGroup(
            SessionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionsPanelLayout.createSequentialGroup()
                .addGroup(SessionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SessionsPanelLayout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(ListLabel))
                    .addGroup(SessionsPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(215, Short.MAX_VALUE))
        );
        SessionsPanelLayout.setVerticalGroup(
            SessionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SessionsPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 553, Short.MAX_VALUE)
                .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChampPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 900, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(ChoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LastChampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SessionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ChampPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(ChoicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(LastChampPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(SessionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 674, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        this.dispose();    
        System.exit(0);
    }//GEN-LAST:event_ExitButtonActionPerformed

    private void BeginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeginButtonActionPerformed
        startForm();
        init();    
    }//GEN-LAST:event_BeginButtonActionPerformed

    private void RightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RightButtonActionPerformed
        click=true;
        count=1;
        next();
    }//GEN-LAST:event_RightButtonActionPerformed

    private void LeftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeftButtonActionPerformed
        click=true;
        count=0;
        next();
    }//GEN-LAST:event_LeftButtonActionPerformed

    private void SessionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SessionButtonActionPerformed
       //кнопка предыдущих сеансов:
       if (tournament.numOfRound()==0){
           showMessageDialog(null,"Журнал пуст! Нет доступных сессий");
    }
     else{
          //загружаем лист - список доступных (ранее сыгранных) игр
           ChampPanel.setVisible(false);
           ChoicePanel.setVisible(false);
           MainPanel.setVisible(false);
           LastChampPanel.setVisible(false);
           func();
           SessionsPanel.setVisible(true);
          
       }
    }//GEN-LAST:event_SessionButtonActionPerformed
    void func(){    //отображение листа игр(сессий)
    JButton[] buttons = new JButton[tournament.numOfRound()];
    //динамическое создание кнопок
    int sp=0;   
    for(int i=0; i < buttons.length; i++)  {
    buttons[i] = new JButton("Игра № " + (i+1) );
    buttons[i].setBounds(60+sp, 100, 150, 150);
    sp+=200;
    SessionsPanel.add( buttons[i]);
    buttons[i].addActionListener(new ActionListener(){ // если щелчек был, то выполняем actionPerformed 
    public void actionPerformed(ActionEvent e) { //e - ссылка на кнопку 
        String choice = e.getActionCommand(); //получаем имя кнопки
        //находим число в строке
        Pattern numberPat = Pattern.compile("\\d+"); // регулярные выражения
        Matcher matcher = numberPat.matcher(choice);
        if (matcher.find()) //если matcher что-то нашел
            // patter - макет поиска цифры
        // mather - берет шаблон и накладывает на строку
{       
            int number = Integer.parseInt(matcher.group());  // parseInt переводит из строки в число                                   
            Draw(number);      
}
       }
      });
    }
   }
    
    void Draw(int R){ // R=number
      LastChampPanel.removeAll();
      JButton back=new JButton("Назад");
      back.addActionListener(new ActionListener(){  
      public void actionPerformed(ActionEvent e){
       LastChampPanel.setVisible(false);
       SessionsPanel.setVisible(true);
       
}  
});  
        
      JLabel title=new JLabel("Победитель игры № "+R+ " - "+tournament.getWinnerList().get(R-1));
      title.setBounds(40, 0, 800, 50);
      Font fn = new Font(Font.MONOSPACED, Font.BOLD, 24);
      title.setFont(fn);
      Color c1 = new Color(255,255,0);
      title.setForeground(c1);
      back.setBackground(c1);
      Image img=tournament.getWinnerList().get(R).getImg();
      JLabel champ=new JLabel(new ImageIcon(img));
      champ.setBounds(300, 100, 300, 450);
      back.setBounds(40, 580, 155, 50);
      back.setFont(fn);
      LastChampPanel.add(back);
      LastChampPanel.add(title);
      LastChampPanel.add(champ);
      LastChampPanel.setVisible(true);
      SessionsPanel.setVisible(false);
      
    }
     
    
    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
       SessionsPanel.setVisible(false); 
       MainPanel.setVisible(true);   
    }//GEN-LAST:event_BackButtonActionPerformed

    private void EndButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EndButtonActionPerformed
        ChampPanel.setVisible(false);
        MainPanel.setVisible(true);
    }//GEN-LAST:event_EndButtonActionPerformed

    private void AgainButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgainButtonActionPerformed
        startForm();
        init();
    }//GEN-LAST:event_AgainButtonActionPerformed

    void startForm(){       //загрузка главной формы с кнопками выбора
     MainPanel.setVisible(false);
     ChampPanel.setVisible(false);
     SessionsPanel.setVisible(false);
     ChoicePanel.setVisible(true);
     tournament.start();
    }
    
    /**
     * @param args the command line arguments
     */

    void init(){
        //функция инициализция - отображение стартовых обложек фильмов
         LeftButton.setIcon(new ImageIcon(mc.getMovies().get(0).getImg()));
         RightButton.setIcon(new ImageIcon(mc.getMovies().get(1).getImg()));
         LeftLabel.setText(mc.getMovies().get(0).getTitle());
         RightLabel.setText(mc.getMovies().get(1).getTitle());
   }

     public int getValue(){ // какую кнопку мы нажали
        return count;
    }
    void next(){
   
        tournament.getElements();  //проверим есть ли еще элементы?
        if(click && tournament.getPairs()>=1){  //если нажата какая то из кнопок, мы должны запустить и показать
           //следующую пару для просмотра и выбора
           //и есть еще пары для отображения 
        init();
        click=false; 
         }
        else{
            Winner();  
        }
      
    }
    
    void Winner(){

        //Image res=tournament.getWinnerList().get(0).getImg();
        //String res1=tournament.getWinnerList().get(0).getTitle();
        //WinnerButton.setIcon(new ImageIcon(res));
        ChoicePanel.setVisible(false);
        MainPanel.setVisible(false);
        ChampPanel.setVisible(true);
    }
       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgainButton;
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BeginButton;
    private javax.swing.JLabel ChampLabel;
    private javax.swing.JPanel ChampPanel;
    private javax.swing.JLabel ChoiceLabel;
    private javax.swing.JPanel ChoicePanel;
    private javax.swing.JButton EndButton;
    private javax.swing.JButton ExitButton;
    private javax.swing.JPanel LastChampPanel;
    private javax.swing.JButton LeftButton;
    private javax.swing.JLabel LeftLabel;
    private javax.swing.JLabel ListLabel;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton RightButton;
    private javax.swing.JLabel RightLabel;
    private javax.swing.JButton SessionButton;
    private javax.swing.JPanel SessionsPanel;
    private javax.swing.JButton WinnerButton;
    // End of variables declaration//GEN-END:variables
}

